<?php
$data = $block->getFormUrl();
?>
<form style="padding: 1rem; margin-top: 1rem; border: 1px solid silver" method="POST" action="<?php echo $block->getAddUrl() ?>" >
        <h3>Add New Employee</h3>
        <div>
            <label>Name</label>
            <input name="name" type="text" />
        </div>
        <div>
            <label>Email</label>
            <input name="email" type="text" />
        </div>
        <div>
            <label>Mobile No</label>
            <input name="mobile" type="text" />
        </div>
        <div>
            <label>Date of Birth</label>
            <input name="dob" type="date" />
        </div>
        <div>
            <label>Address</label>
            <textarea name="address"></textarea>
        </div>
        <div>
            <label>Date of Joining</label>
            <input name="doj" type="date" />
        </div>
        <button>Submit</button>
    </form>